<?php
    // Touch this and <me> will come over to your desk and staple your bottom lip to your keyboard.
    // Autogenerated variables, do not edit. All changes will be undone
    // You better understand Sarcasm, you Nerd!!

    // Some constants
    class Config
    {

        /********************************* SITE PATHS *********************************/
        const DEVELOPMENT_URL = 'http://mediwise.work/src/public';
        const PRODUCTION_URL = 'http://medywise.com';
        const ADMIN_URL = 'http://mediwise.work/src/admin';

        /********************************* MAILTRAP CREDNTIALS *********************************/
        const SMTP_MAILTRAP_HOST = 'smtp.mailtrap.io';
        const SMTP_MAILTRAP_USER = '53baafaffb25bd';
        const SMTP_MAILTRAP_PASSWORD = '82766d0cd3b91c';
        const SMTP_MAILTRAP_PORT = 2525;

        /********************************* SEND EMAIL TO USER/NEW ADMIN CREDNTIALS *********************************/
        const SMTP_GOOGLE_HOST = 'smtp.gmail.com';
        const SMTP_GOOGLE_EMAIL = 'info.medywise@gmail.com';
        const SMTP_GOOGLE_PASSWORD = 'symptomstinking';
        const SMTP_GOOGLE_PORT = 587;

        /********************************* LOGIN WITH GOOGLE CREDNTIALS *********************************/
        const API_GOOGLE_CLIENT_ID = '830487944456-4c0ccr1h1s04s9l3au1hlkq77f15o13m.apps.googleusercontent.com';
        const API_GOOGLE_CLIENT_SECRET = 'Amf5dIjJuI63BO63d7MEECfG';
        const API_GOOGLE_APP_NAME = 'Medywise';
        const API_GOOGLE_REDIRECT_URI = 'http://localhost/medicine/src/api/google/g-callback.php';
        const API_GOOGLE_SCOPE = 'https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email';

        /********************************* LOGIN WITH FACBOOK CREDENTIALS *********************************/
        const API_FACEBOOK_APP_ID = '209782113001103';
        const API_FACEBOOK_APP_SECRET = 'b3b91d80dc1c6f05ed4c8c54760d4bd8';
    }//End of Class
